// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_cah264.Models;

namespace Mission06_cah264.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230209034501_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_cah264.Models.FormResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Sci-fi/Adventure",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = "PG13",
                            Title = "Interstellar",
                            Year = (short)2014
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Comedy",
                            Director = "Jared Hess",
                            Edited = false,
                            Rating = "PG",
                            Title = "Napoleon Dynamite",
                            Year = (short)2004
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "War/Drama",
                            Director = "Mel Gibson",
                            Edited = false,
                            Rating = "R",
                            Title = "Hacksaw Ridge",
                            Year = (short)2016
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
